### ISSUE TITLE
Spaceship is losing health after spawning if there is an asteroid already at the spawn position

### ISSUE THREAD

**Issue by j-tesla** [j-tesla/space-shooter#15]
Give it a small time interval after spawning before it can be hit by a asteroid. 
Make it blink in that time interval

**Comment by codephile1221** [comment]
Hello 👋
I would like to work on this issue.
I have two disclaimers though: I'm new to contributing and I haven't touched pygame in a long time.

**Comment by AshAman999** [comment]
Hello, though i am new, still i have made little changes,like ability to shoot with the left mouse click.
Tried to fix this issue but couldn't.
If you would like to merge the changes that i mentioned above, then i could make a pull request.........

**Comment by codephile1221** [comment]
@AshAman999  How about making a new issue for yourself?
That will keep things separate and makes tracking new changes easier.
You could also directly make a PR.

**Comment by j-tesla** [comment]
@codephile1221 sure, give it a try.

**Comment by AshAman999** [comment]
> @AshAman999 How about making a new issue for yourself?
> That will keep things separate and makes tracking new changes easier.
> You could also directly make a PR.

i am kinda new to github, so i thought it would be better if i would just ask

**Comment by desai10** [comment]
Hey sorry @codephile1221 I had already started working on this and I forgot to post a message over here about that! :-/ Sorry about that. I already raised the PR for this (https://github.com/j-tesla/space-shooter/pull/18)

**Comment by codephile1221** [comment]
dang, I was working on it too.
I'll submit a PR when I'm done anyway, if at all I do manage to finish it 😅.

**Comment by codephile1221** [comment]
You know what, nvm. I'll check out some other issue. Not gonna submit a PR for this issue.
