### ISSUE TITLE
add Back To Menu after game over

### ISSUE THREAD

**Issue by codephile1221** [j-tesla/space-shooter#30]
Currently the only action that can be done at the GAMEOVER screen is to close the window.
I would like to implement a "Back to Menu" and maybe even an "Play Again" button.

It would be highly appreciated if this issue can be assigned to me as I have already started working on it.

**Comment by j-tesla** [comment]
@codephile1221 sure, go I head. :rocket:  I thought of implementing that too, but I didn't find any time.

**Comment by codephile1221** [comment]
Alright, thanks

**Comment by codephile1221** [comment]
Just checking in,
It will take me more time as I'm busy with stuff.

**Comment by codephile1221** [comment]
Checking in again,
almost done!
