### ISSUE TITLE
Classify Repo with Hacktober Topic

### ISSUE THREAD

**Issue by codephile1221** [j-tesla/space-shooter#31]
As per the new Hackoberfest rules update, the repos need to have "Hacktoberfest" in the topic in order for the PRs to count towards Hacktoberfest.

source: https://hacktoberfest.digitalocean.com/hacktoberfest-update

I'm assuming you don't have any problem with it as you have labelled some of the issues in this repo as "Hacktoberfest".
The link I've sent also has instructions on how to do the same.

**Comment by j-tesla** [comment]
@codephile1221 thanks, man!
