### ISSUE TITLE
[bug] local variable 'click' referenced before assignment

### ISSUE THREAD

**Issue by codephile1221** [j-tesla/space-shooter#34]
I have encountered a bug at the launch of the program where I get the following error and the program stops.
```python
Traceback (most recent call last):
  File "main.py", line 571, in <module>
    main_menu()
  File "main.py", line 59, in main_menu
    if click:
UnboundLocalError: local variable 'click' referenced before assignment
```

This can be reproduced by putting the mouse pointer in the region of `play` or `instructions` button and then running the program.
Since collidepoint() will return True, the [conditional statement inside](https://github.com/j-tesla/space-shooter/blob/ab0230de08056413aeb7b22f26704a6c1ba697e9/main.py#L59) gets executed.

This bug can be fixed by either moving [click = False](https://github.com/j-tesla/space-shooter/blob/ab0230de08056413aeb7b22f26704a6c1ba697e9/main.py#L69) higher up or by rewriting the program and putting the event loop further down or putting the collidepoint() check inside the event of [MOUSEBUTTONDOWN](https://github.com/j-tesla/space-shooter/blob/ab0230de08056413aeb7b22f26704a6c1ba697e9/main.py#L78)

The first way is easiest, however I feel the third method is "correct" way of doing it because:
1) there need not be checking whether the mouse is in the region of `play` or `instructions` button at that point in the program, and 
2) it will lead to the elimination of the variable `click`

**Comment by codephile1221** [comment]
Of course, I would be happy to make the necessary changes.

**Comment by j-tesla** [comment]
@codephile1221, feel free to fix it.
