### ISSUE TITLE
Asteroids disappearing on collision with immune ship

### ISSUE THREAD

**Issue by j-tesla** [j-tesla/space-shooter#44]
Asteroids shouldn't disappear when they hit the ship just after it spawns. They need to pass through the ship. Previous updated (#18) managed to prevent the explosion and health reduction. (#15)

```python
        hits = pygame.sprite.spritecollide(player, mobs, True,
                                           pygame.sprite.collide_circle)
```

The `True` in there is causing this. Figure out a way to make it `False` without changing causing any effects.

**Comment by souravmondal13** [comment]
I want to work on this issue, please assign this to me
