### ISSUE TITLE
Save highscores

### ISSUE THREAD

**Issue by j-tesla** [j-tesla/space-shooter#6]
For starters, can store 'the highscore' in a txt file (or a json file). Can be updated if required after each game.

**Comment by mxw7265** [comment]
I can give it a shot. I would use json file since it's easier to work with.

**Comment by j-tesla** [comment]
@mxw7265 Sure! Don't forget to display the high-score somewhere at the top of the screen during the game too.

**Comment by mxw7265** [comment]
I should be able to complete this weekend. I am busy at the moment. Sorry!

**Comment by j-tesla** [comment]
@mxw7265 there's no hurry. I'm busy too.
